version: '3'
services:
  api:
    build: .
    command: lein ring server
    ports:
    - "3000:3000"
    volumes:
    - ./src:/api/src

  apitest:
    build: .
    command: lein test
    volumes:
    - ./src:/api/src
    - ./test:/api/test
