version: '3'
services:
  api:
    build: .
    command: lein ring server-headless
    ports:
    - "3000:3000"
    volumes:
    - ./src:/api/src

  apitest:
    build: .
    command: lein test-refresh
    volumes:
    - ./src:/api/src
    - ./test:/api/test
    - ./resources/:/api/resources

  api-ci:
    build: .
    command: bash -c "lein cljfmt check && lein test"
    volumes:
    - ./src:/api/src
    - ./test:/api/test
    - ./resources/:/api/resources
